function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "calculater_sub_sys"};
	this.sidHashMap["calculater_sub_sys"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "calculater_sub_sys:11"};
	this.sidHashMap["calculater_sub_sys:11"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "calculater_sub_sys:1"};
	this.sidHashMap["calculater_sub_sys:1"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Input1"] = {sid: "calculater_sub_sys:2"};
	this.sidHashMap["calculater_sub_sys:2"] = {rtwname: "<Root>/Input1"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "calculater_sub_sys:11"};
	this.sidHashMap["calculater_sub_sys:11"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "calculater_sub_sys:7"};
	this.sidHashMap["calculater_sub_sys:7"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "calculater_sub_sys:8"};
	this.sidHashMap["calculater_sub_sys:8"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "calculater_sub_sys:9"};
	this.sidHashMap["calculater_sub_sys:9"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "calculater_sub_sys:10"};
	this.sidHashMap["calculater_sub_sys:10"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<S1>/Input"] = {sid: "calculater_sub_sys:12"};
	this.sidHashMap["calculater_sub_sys:12"] = {rtwname: "<S1>/Input"};
	this.rtwnameHashMap["<S1>/Input1"] = {sid: "calculater_sub_sys:13"};
	this.sidHashMap["calculater_sub_sys:13"] = {rtwname: "<S1>/Input1"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "calculater_sub_sys:3"};
	this.sidHashMap["calculater_sub_sys:3"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Divide"] = {sid: "calculater_sub_sys:4"};
	this.sidHashMap["calculater_sub_sys:4"] = {rtwname: "<S1>/Divide"};
	this.rtwnameHashMap["<S1>/Multiply"] = {sid: "calculater_sub_sys:5"};
	this.sidHashMap["calculater_sub_sys:5"] = {rtwname: "<S1>/Multiply"};
	this.rtwnameHashMap["<S1>/Subtract"] = {sid: "calculater_sub_sys:6"};
	this.sidHashMap["calculater_sub_sys:6"] = {rtwname: "<S1>/Subtract"};
	this.rtwnameHashMap["<S1>/Output"] = {sid: "calculater_sub_sys:14"};
	this.sidHashMap["calculater_sub_sys:14"] = {rtwname: "<S1>/Output"};
	this.rtwnameHashMap["<S1>/Output1"] = {sid: "calculater_sub_sys:15"};
	this.sidHashMap["calculater_sub_sys:15"] = {rtwname: "<S1>/Output1"};
	this.rtwnameHashMap["<S1>/Output2"] = {sid: "calculater_sub_sys:16"};
	this.sidHashMap["calculater_sub_sys:16"] = {rtwname: "<S1>/Output2"};
	this.rtwnameHashMap["<S1>/Output3"] = {sid: "calculater_sub_sys:17"};
	this.sidHashMap["calculater_sub_sys:17"] = {rtwname: "<S1>/Output3"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
